### ISSUE TITLE
Idle web-based nunuStudio causes high GPU load

### ISSUE THREAD

**Issue by user1713952** [tentone/nunuStudio#10]
Steps to reproduce the issue:

1) start a local webserver (i use WebServer for Chrome)
2) open nunuStudio/source/editor.html
3) fire up TechPowerUp
4) observe the high GPU load (here 70%)

![2icgdurh](https://cloud.githubusercontent.com/assets/3883114/23409325/7f273cca-fdcb-11e6-89f8-5b2f3922705d.jpg)

On my desktop PC it is not really an issue, but on my laptop it causes the fans to vigorously spin with the corresponding noise.

Maybe something can be done to reduce the idle load?

Hardware: 

- [GeForce 750Ti ](https://www.techpowerup.com/gpudb/2548/geforce-gtx-750-ti)on PC
- [Intel HD Graphics 5500](https://www.techpowerup.com/gpudb/2625/hd-graphics-5500) on Laptop

**Comment by tentone** [comment]
Hi @user1713952

Can you please try to run the version available at doc/editor folder, just to check if the minified version has some impact. Probably it will not.

I will have to do some testing myself and take some time to find what is causing that GPU load.

Thanks a lot for reporting it.

Cumps

**Comment by user1713952** [comment]
Hi @tentone 

Thanks for the feedback. Unfortunately the problem still occurs.
![image](https://cloud.githubusercontent.com/assets/3883114/23415208/d339bb4a-fdde-11e6-9a6a-f10bdc264bdd.png)

BR
M.

**Comment by tentone** [comment]
Thanks for checking

I will not be able to check this today, but as soon as i do it i will let you know.

**Comment by user1713952** [comment]
No worries, no rush! I am grateful that you are considering it. Thanks again for your great work and for sharing it too!

**Comment by diamondo25** [comment]
You could possibly give us a trace from the JavaScript Profiler inside the Chrome Web Inspector (F12), that would help us.

**Comment by tentone** [comment]
@user1713952 Hi there

I have been refactoring some code inside nunu to avoid creating so many webgl contexts and removed the global update cycle.

This helped to reduce GPU usage a bit, (not much, its around 10~20% on my laptop Intel HD5100 IDLE).

Even though it is indicated as GPU use we always have to take into account that the GPU is in the minimum profile of performance. The use of GPU is measured in GPU time spent, so a GPU in idle 40% is reasonably normal given the low clock frequency.

In the case of the threejs editor, for example the GPU usage goes to zero because if the camera is stopped it stops rendering (it avoids rendering the same image several times).

Thanks, i hope this have helped 

Cumps
