### ISSUE TITLE
i.e. 11compatibility

### ISSUE THREAD

**Issue by 68chase** [tentone/nunuStudio#147]
# i.e. 11 Compatibility

##### Description
 - I just realized published content is not running in i.e. 11.  Has anyone found any setting or workaround to get it to work in i.e. 11.  I am running the most current version of i.e.

I now realize the i.e, is not supported, but just wondering if by any chance has anyone got it to work.

Thanks
Aaron

#### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi

Internet explorer 11 is not supported by nunuStudio, IE lacks support for a lot of modern web API and its a bit hard to get it to fully work with nunuStudio.

Some older version worked with it but i had to leave support for IE eventually in order to adopt new "better" web API's.

The last stable version of IE 11 is now 3 years old, accoding to https://www.w3counter.com/globalstats.php IE11 is now used by less than 4% of the internet users, if youre a web dev dont worry!

Thanks a lot!

Cumps
