### ISSUE TITLE
Environment Map - Material Editor

### ISSUE THREAD

**Issue by weekendkoder** [tentone/nunuStudio#153]
Environment Map 

##### Description
When i try to set a environment map, it doesn´t work. So i am not able to select a texture for my
Material. Do you know if i am missing something ? Or do you have any sample scene ?

##### Version
v0.93
##### Platform
Windows 8 , NodeJS

**Comment by tentone** [comment]
To add an enviroment map, first create a CubeTexture (in the assset explorer, Texture/Cube Texture), after you can double click the new texture to open the CubeTexture editor.

That cube texture can be applied as enviroment map.

I will add a warning message so that people know this when they try to add a normal texture.

Thanks a lot.

Cheers

**Comment by weekendkoder** [comment]
Phew, and i thought it is a bug, or so. Will try your procedere as soon, as possible. Thank you.
