### ISSUE TITLE
Physics bug

### ISSUE THREAD

**Issue by Bethleem** [tentone/nunuStudio#177]
Hi.

First, congratulations. The editor just looks superb. :)

Then, I was playing around with it and when you add a physic body to a object in the right-click menu, the body doesn´t fit the object is supposed to, is created displaced from it. Rather annoying.

A suggestion: could, in a distant future, be that the editor support different open source html5 engines? Likes playcanvas or babylon. One editor, several game engines.

Regards,

Belén M.

**Comment by tentone** [comment]
Hi

Thanks a lot. Currently the physics body does not match the transformation of the object.

I will try to fix soon for new next release.

Its a bit hard since nunuStudio is really tied to threejs, fortunatelly threejs is already a great graphics engine. I might move physics in the future from cannonjs to ammojs (interchangable).

Thanks a lot for reporting this.

**Comment by tentone** [comment]
Hello

This bug was been fixed in the meanwhile when you create a physics body it now matches the object transform properly.

Thanks a lot!

Cheers
