### ISSUE TITLE
Allow standalone nwjs builds

### ISSUE THREAD

**Issue by keleko34** [tentone/nunuStudio#22]
Allow the ability to build the final game into a standalone nwjs app as well rather than just for the web.

**Comment by tentone** [comment]
HI @keleko34 

The desktop version is able to export standalone NWJS apps for windows linux and osx. In the future is the project has any kind of success i might add also cordova for mobile.

As always i recommend people to be careful when selecting nunu or any other web based engine for developing desktop games, since there is a big performance penalty.

I hope this has helped. Thanks.

Cumps
