### ISSUE TITLE
Remove the build/ folder from the repository

### ISSUE THREAD

**Issue by AndrewRayCode** [tentone/nunuStudio#25]
Git is mainly for source code, not built code. Every time you update that file you're adding megabytes of data to the history, none of which is needed. It's better to get this fixed early on than lock into it later.

**Comment by tentone** [comment]
Hi @AndrewRayCode 

I actually already considered to remove the builds from the repo (i had already some problems because i was storing NWJS bins here), but since im not using any common package manager and my build system only runs on windows i decided to distribute builds here to make it easier for everybody to access dev builds.

In the future i might consider moving this to an external bulding server.

Thanks a lot

Cumps.
