### ISSUE TITLE
Old threejs version

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#317]
# Old threejs version

##### Description
- does any one know how to update the threejs vertion in ``nunu.min.js``
- or can ``tentone`` update the the threejs in ``nunu.min.js``
- the later threejs version is ``r112`` the one in ``nunu.min.js`` is ``r104``
- if u can also update the other libraries too

##### Version
 - <0.9.5>
BETA [X]

##### Others
needs update [X]

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Since there is a big chance of breaking stuff on nunuStudio when updating to new versions of libraries i try to update them myself using the update script.

Usually i update the threejs version at least once a month. I will check is nunu.min.js is also being updated as it should.

We could also move the libs to separate files and let people update them manually if they want to. But at that point i would have to manage library backwards compatibility.

Thanks a lot for reporting this situation.

**Comment by Hoodgail** [comment]
yes seperating the main libs such as three.js and cannon.js etc is better i think

**Comment by tentone** [comment]
That could also be an option at least for three, im considering to fork cannon into a new lib using three tree structure and math libs to simplify code

**Comment by Hoodgail** [comment]
sounds great 😃 ... thank you
