### ISSUE TITLE
nunustudio messed up in the 2/14/2020 or previous update

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#337]
# nunustudio messed up in the 2/14/2020 or 6 days ago's update

##### Description
 - Hey idk what u did in the nunustudio in the <2/14/2020> or previous update
**BUT** u really need to revert it back
- cuz everything is wrong with cannon and the physics bodies etc
- since i downloaded a previous version on my laptop imma just use it for now :) thank you 
![image](https://user-images.githubusercontent.com/45743294/74580194-512ba380-4f6f-11ea-998d-a924b2255f4d.png)
everytime i'm trying to rescale it i just shrinks back to the small size and many more... i have a previous project... **EVERY PHYSIC SHAPES** is messed up... and i its gonna take a lot of time re fixing it/ and currently impossible atm cuz it keeps sizing back to the small size everything i try to make it bigger 

##### Version
 - < 6 days ago's update> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

In the last update i have introduces two physics modes for positioning im trying to work on a better solution to handle physics world to tree coordinates. You have now two physics modes:

World -> The coordinates are copied directly from physics objects to the tree.
Local -> The coordinates are recalculated every frame and converted from tree transform to physics world and vice versa.

Originally it was using a mixed mode, probably by switching to local mode your game should work as it was before (it is a bit slower but keeps object positioning consistent even when objects are deep in the tree), please try it out, otherwise i can re-add the original mixed mode to prevent problems.

Thanks a lot

**Comment by Hoodgail** [comment]
> Hello
> 
> In the last update i have introduces two physics modes for positioning im trying to work on a better solution to handle physics world to tree coordinates. You have now two physics modes:
> 
> World -> The coordinates are copied directly from physics objects to the tree.
> Local -> The coordinates are recalculated every frame and converted from tree transform to physics world and vice versa.
> 
> Originally it was using a mixed mode, probably by switching to local mode your game should work as it was before (it is a bit slower but keeps object positioning consistent even when objects are deep in the tree), please try it out, otherwise i can re-add the original mixed mode to prevent problems.
> 
> Thanks a lot

aaaah i didnt know... ok ill try thank thank you
