### ISSUE TITLE
Scene only renders in 1/4 of the available screen during run mode

### ISSUE THREAD

**Issue by helzapps** [tentone/nunuStudio#360]
# Scene only renders in 1/4 of the available screen during run mode

##### Description
After [issue 359](https://github.com/tentone/nunuStudio/issues/359) was fixed when I run my scene only 1/4 of it displays.
I tested on the default scene when you just load the default editor and it does not happen with this one. But I tested opening a few of the sample projects on the nunustudio.org home page and they do the same thing.
<img width="2521" alt="Screen Shot 2020-04-09 at 5 38 01 PM" src="https://user-images.githubusercontent.com/1172574/78952423-4f232400-7a8a-11ea-9eae-3488583dfef6.png">

##### Version
0.9.6 Build 202004100016

##### Platform
 - Web Version [X]
 - Windows [ ]
 - Linux [ ]

**Comment by helzapps** [comment]
Sorry, should mention that the same preconditions apply to this as in issue 359, macOS on retina displays.

**Comment by tentone** [comment]
Hello

I will have to check more carefully whats happening on the last bug it was actually behaving wrong because it was considering the render resolution for raycasting and viewport.

If the devicePixelRatio is different from 1.0 the render resolution has to be different in order to ensure that there is a 1:1 render pixel quality being displayed.

You're running a dual display setup correct? Could you please check in the console the value of window.devicePixelRatio when the window is in each of the screens?

The value should be different for each screen since MacOS can use different settings for each one of them. (Should be about 2.0 on the retina screen i think and 1.0 on the regular one).

I probably have to be constantly checking for changed in this value to update the rendering config.

A easy fix would be to allow nunuStudio to ignore devicePixelRatio but that would make the image slightly pixelated on the retina display. Hope that we can find a better solution.

Thanks a lot once again.

**Comment by helzapps** [comment]
So I personally have a MacBook Pro with Retina display (mid 2017), but then my second monitor is the LG 5K monitor, so for both monitors the 
`console.log("window.devicePixelRatio = " + window.devicePixelRatio);`
prints:
`window.devicePixelRatio = 2.0`

One my developers on my team has been using an HD monitor for months for nunu apps we build and never reported the bug. But I had to take on one of his projects and when I showed him the original bug that's when he told me "oh yeah my 5K iMac does that, so I just do nunu projects on an old 1080HD monitor". I would say that that this bug is _less_ critical assuming the exported version (I haven't tested) runs just fine when I embed it into our web app. My other developer is off for the night, but I can have him check tomorrow what his HD monitor is outputting with the latest build/version. I'm guessing 1.0.

**Comment by tentone** [comment]
I will try another solution that i unfortunately cannot test, but should work fine.

Apparently we can detect pixel ratio changes when the page moves between screens using https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio.

**Comment by tentone** [comment]
Just another question if you resize the window does it fix the rendering size by itself? Thanks a lot

**Comment by helzapps** [comment]
The run panel resizes, but it still only ever renders in the bottom left corner.

**Comment by tentone** [comment]
I have published a new version with a fix, that should detect when the app changes screen to adjust the pixel ratio value.

If it does not work i also added an option in the settings general tab to ignore the pixel ratio value that should work if the first solution does not solve it.

Thanks a lot for the help.

**Comment by helzapps** [comment]
In settings `Ignore Device pixel ratio` = true: ✅ 
Running without that set and changing the window size: 🚫 

So with the workaround of just setting it to true, I would mark this as fixed IMO. The pixelation from ignoring the device pixel ratio on there retina display is barely noticeable IMO as well.
I'll leave it up to you to open another bug and pursue investigating and fixing it so that you can autodetect the specific monitors pixel ratio and adjust accordingly. Closing this issue.

If you need a tester for your macOS app, or macOS in general, I'm happy to be added to a list 👍
