### ISSUE TITLE
How to apply collision with terrain?

### ISSUE THREAD

**Issue by KCGD** [tentone/nunuStudio#411]
The terrain tool looks awesome, just wondering how to apply collision to the terrain, like making it an object that other objects can use as a sort of floor / ground

this is in the web version 0.97.14

thanks!

**Comment by tentone** [comment]
Hello

Its still not possible to implement terrain collision from the terrain object but it will be implemented soon, since its a pretty straight forward feature to implement we just need to copy the terrain elevation to a CANNON terrain shape and should work fine.

Thanks a lot. Hope to implement it soon.

**Comment by lookmister** [comment]
Hi,
Are you still considering adding this? would be super useful!

**Comment by tentone** [comment]
Yes, i intent do move first to cannon-es that is the currently maintained branch of cannon and implement these.

Thanks a lot!

**Comment by bil-ash** [comment]
Any updates on this? Actually, I also need to use this feature.
Since upgrade to cannon-es from cannon.js has already been made, hoping to see this feature soon.

**Comment by tentone** [comment]
Hello.

Currently nunuStudio is already using cannon-es wich should support this feature. I believe that it is already available on the platform.!

Thanks a lot!
