### ISSUE TITLE
Devtools no longer open on macOS

### ISSUE THREAD

**Issue by denkerinteraktivgmbh** [tentone/nunuStudio#425]
# Devtools no longer open on macOS

##### Description
- The Chrome-devTools-window no longer opens with the nwjs-build for macOS. I'm not shure if this problem occures on Windows as well.

##### Version
 - nunuStudio 0.98.12 Build 2020-08-01T07:59:57.316Z

##### Platform
 - Web Version []
 - Windows []
 - Linux []
 - MacOS [x]

**Comment by denkerinteraktivgmbh** [comment]
Note: F12-Shortcut ist working. "Cmd+Alt+I"-Shortcut and Menubar->Window->devTools isn't.

**Comment by tentone** [comment]
Hello

Unfortunately, I don't have any means to test this issue since I don't own a macOS based computer.

This might be a nwjs issue. I would recommend moving to the web version when using macOS. 

You can try the win.showDevTools() function to open the dev tools, ensure that you are running an SDK flavor or NWJS otherwise dev tools will not be available.

Thanks a lot!
