### ISSUE TITLE
Image is distorted when imported

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#54]
I dragged and dropped an image of a vase (768x1536) from the right, but it looks distorted when imported. Is this intentional? If so, why? Would you consider altering it to make it work as expected? It's a little inconvenient.

![image](https://cloud.githubusercontent.com/assets/180382/26365084/73210d2a-3fde-11e7-890e-bfab94502e64.png)

**Comment by tentone** [comment]
Hi, it is actually on purpose for a texture is does not matter the aspect ratio since they are mapped to triangles in 3D geometries.

But sometimes it comes handy to have an option to make the texture follow the aspect ratio for 2D sprites, i will try to figure out the best way to have some fast option the calculate those to make the texture fit with corrent aspect ratio in the square or maybe add an option to force sprites size to follow the aspect ratio.

Thanks for the suggestion.

**Comment by tentone** [comment]
HI added a new option to the texture assets to automatically calculate offset and repeat value to fit the image aspect ratio, as i said above i think it migth come handy for 2D sprites, but should not be used for 3D geometries.

![capture](https://cloud.githubusercontent.com/assets/9158354/26446502/3a0d7f00-413c-11e7-8766-adf7e8a6ff56.PNG)
