### ISSUE TITLE
Programatically create objects

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#66]
How do I programatically create text objects (and any other object really) in NunuStudio?

I've been using THREE.js geometries (e.g. CircleBufferGeometry, PlaneBufferGeometry) directly when I need to create objects programatically. But the [text geometry](https://threejs.org/docs/#api/geometries/TextGeometry) asks for a bit too much configuration, so I'm wondering if NunuStudio offers wrappers around geometries?

Or should I continue using THREE.js geometries directly?

**Comment by tentone** [comment]
Hi 

Check the nunu docs there is a dedicated Text3D object that receives font and text as arguments.

nunu has wrapper for some of the threejs obejcts textures etc  some of then are a bit diferent (texture for example use the nunu resources instead of requiring loaders for resouces)

I hope this helps.

Cumps
