### ISSUE TITLE
Thoughts on Vizor Patches?

### ISSUE THREAD

**Issue by brylie** [tentone/nunuStudio#85]
What are your thoughts on the Vizor Patches project? Might the Vizor node-based programming interface complement NunuStudio?

https://github.com/vizorvr/patches

**Comment by tentone** [comment]
I have considerered include support for visual scripting tools in nunuStudio(initially i was thinking about using google blockly), right now im more focused on polishing existing features, work a bit on UI and animations but i want to come back to this later down the road.

Vizor patches looks like a really promising framework.

Thanks a lot for sharing it.

Cumps

**Comment by Gurigraphics** [comment]
I also prefer Google Blockly.

Some disadvantages of '**wires visual approach**' are: 

difficult to organize, to do maintenance, to improve, to replicate or reproduce, to reuse or share, to work as a team, etc.

Let's use this textual code example:

`func _process (delta): translation + = speed * delta;`

The Stencyl/Scratch standard to doing something like this:
http://i.imgur.com/hm0VaOX.png

The Billion of different ways to make a Spaghetti with Godot/Unreal wires visual approach:
http://imgur.com/8Faobh0.png

Stencyl/Scratch/Blockly it's much more Convention over Configuration - CoC

Anyway, this **Vizor** looks much better organized than traditional wires.

I thought about something like this, just to modularize the code and write complex app without using import, export, require. Or without React, Angular, Backbone, Ember, Vue, etc.
https://www.youtube.com/watch?v=dkAN0FeAKM0

My last prototype is this:
https://www.youtube.com/watch?v=naAcTPbakU0

**Comment by brylie** [comment]
I was also wondering whether the Patches visual interface could be used for a node-base compositing workflow, ala Blender. Thoughts?

**Comment by tentone** [comment]
For audio effects, materials composers, etc, nodes based visual systems like Patches is the way to go in my opinion. Typically for this kind of application not a lot of nodes are used and the final design is really clean easy to understand and easy to change/improve.

For programming, nodes dont work so well, typically a lot of nodes are required even for a small program and it ends up in a big mess.

For visual programmind i typically prefer to have "lists" of blocks (like blocky and game maker have), is it easier to understand.

**Comment by Gurigraphics** [comment]
I thought that "wires" was totally inferior to "blocks". But, testing my editor, I realized that "wires" is very useful to think the software project structure. It could replace the UML diagrams and all be done in the same place.

So, I think the code editor of the future will can have the 3 approaches. 
But, fully integrated. Because, as written above, each approach is best for one thing:

**Code**: to fast edit and copy past code snippets
**Block**: to sort, drag order, change groups and organize modules
**Wires**: to design systems and global configs

Like MVC in the original sense (m of mental model, mind map) or then:
code: particle/cell
block: atom/ organ
wire: molecule/system

However, this would be more useful for very complex systems. 
Otherwise this would just be more work for little result.
